[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
testpaths = catalog users core
norecursedirs = warehouse_service .venv .git htmlcov
addopts = --nomigrations --cov=. --cov-report=html