# Generated by Django 5.2.17 on 2026-09-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
